### ISSUE TITLE
[Doc][Shadow] Center argument was removed from Shadows

### ISSUE THREAD

**Issue by Ranguna** [Positive07/material-love#18]
In the wiki you wrote that the shadows draw function should be called like this:

``` lua
nine.draw(shadow,x,y,w,h,center,pad,depth)
```

Ex:

``` lua
nine.draw(shadow,0,0,100,100,false,false,5)
```

But when the function is called like this the shadow depth will always be set to the default which is 1.
The problem is that the draw function doesn't take the argument 'center' and instead skips from 'h' to 'pad', so in the exemple above the depth variable would be set to false and the 8th argument would be discarded.
Notice in your code that you don't have the 'center' variable in your arguments https://github.com/Positive07/material-love/blob/master/libs/nine.lua#L137

To fix this either change the wiki or add the center functionality to the draw function.

**Comment by pablomayobre** [comment]
Yes you are right that is a wiki error!

As you can see this changed from [this](https://github.com/Positive07/material-love/blob/07ba7b796d9064299a3d18f065350a23a99af5c8/libs/nine.lua#L48) commit to the [next one](https://github.com/Positive07/material-love/commit/ade70e1db08c286a225fd33b35ff55a2aa4764a4) because nine.lua got the ability to handle broken línes and the center is now unknown.

The wiki will be updated for 2.0.0 soon so I'm not sure I'll be fixing this, sorry (I'll keep the issue open for reference)

**Comment by Ranguna** [comment]
Ah alright, I'll just remove the center argument from my draw calls then.
Thanks.

**Comment by pablomayobre** [comment]
Fixed the docs. If I ever release 2.0.0 this issue wont exist at all
