### ISSUE TITLE
[Bug][Image] Trying to index a number at line 4

### ISSUE THREAD

**Issue by TangentFoxy** [Positive07/material-love#21]
I took the demo from the first release and replaced the material-love folder with the latest commit in the repository, and:

![screenshot_2016-06-09_16-46-14](https://cloud.githubusercontent.com/assets/15093567/15950283/3acb7476-2e62-11e6-8fb3-98272d4d0bbc.png)

**Comment by pablomayobre** [comment]
Okey I fixed that, but notice that the demo may have other errors since API may have changed, I don't actually remember, also the demo is outdated so it doesnt test spinners and images

**Comment by TangentFoxy** [comment]
Should I create an issue to update the demo / releases? Or no?

**Comment by pablomayobre** [comment]
As you please, I have no problem on having an issue for it. Do you know if the current version works with the latest update?

**Comment by pablomayobre** [comment]
I'm not sure I'll be updating the demo anytime soon, I also pushed some old commits I had lying around that may have broken everyting even more. I should at least update the docs.

But I'm more concerned about the 2.0.0 rewrite which I'm gonna put on it's own repository called Material World soon. It's a complete rewrite since I'm changin everything!

**Comment by TangentFoxy** [comment]
No worries. I haven't been able to get work done on my GUI stuff lately, and I'm about to try a new approach. Thanks for keeping me updated though. ^^
